"""Add video and file paths to Post model

Revision ID: 047fb77135f0
Revises: 6a82179b4a57
Create Date: 2025-04-18 11:08:34.530228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047fb77135f0'
down_revision = '6a82179b4a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('video_url')
        batch_op.drop_column('file_name')
        batch_op.drop_column('image_url')
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('file_path')
        batch_op.drop_column('video_path')

    # ### end Alembic commands ###
