"""Add image_url to Post model

Revision ID: 976d702fdf6d
Revises: bf802de2e545
Create Date: 2025-04-18 16:53:12.474702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976d702fdf6d'
down_revision = 'bf802de2e545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
